---
mariadb_root_password: password
mariadb_replication_user: slave
mariadb_replication_password: h!KDdGrq!Z2cYf!d#n
mariadb_replication_master: "{{ hostvars['db1']['ansible_default_ipv4']['address'] }}"
# UFW custom rules
web1_ip: "{{ hostvars['web1']['ansible_default_ipv4']['address'] }}"
web2_ip: "{{ hostvars['web2']['ansible_default_ipv4']['address'] }}"
ufw_enable: true
ufw_default_input_policy: REJECT
