---
haproxy_ip_server_web1: "{{ hostvars['web1']['ansible_default_ipv4']['address'] }}"
haproxy_ip_server_web2: "{{ hostvars['web2']['ansible_default_ipv4']['address'] }}"
vip_ip: 192.168.43.150
vip_mask: 24
vip_broadcast: 192.168.43.255
