---
# UFW custom rules
web1_ip: "{{ hostvars['web1']['ansible_default_ipv4']['address'] }}"
web2_ip: "{{ hostvars['web2']['ansible_default_ipv4']['address'] }}"
ufw_enable: true
ufw_default_input_policy: REJECT
ufw_rules: [
        { from_ip: "{{ web1_ip }}", port: 111, proto: any, comment: "NFS: allow 111 from {{ web1_ip }}" },
        { from_ip: "{{ web2_ip }}", port: 111, proto: any, comment: "NFS: allow 111 from {{ web2_ip }}" },
        { from_ip: "{{ web1_ip }}", port: 2049, proto: any, comment: "NFS: allow 2049 from {{ web1_ip }}" },
        { from_ip: "{{ web2_ip }}", port: 2049, proto: any, comment: "NFS: allow 2049 from {{ web2_ip }}" }
]
