---
# UFW
lb1_ip: "{{ hostvars['lb1']['ansible_default_ipv4']['address'] }}"
lb2_ip: "{{ hostvars['lb2']['ansible_default_ipv4']['address'] }}"
ufw_rules: [
        { from_ip: "{{ lb1_ip }}", port: 80, proto: tcp, comment: "HTTP: allow from {{ lb1_ip }}" },
        { from_ip: "{{ lb2_ip }}", port: 80, proto: tcp, comment: "HTTP: allow from {{ lb2_ip }}" }
]
vhost_alias: wordpress.example.local
vhost_root_directory: /var/www/wordpress
vhost_log: /var/log/apache2/wordpress.log
vhost_conf_file: wordpress
nfs1_ip: "{{ hostvars['nfs1']['ansible_default_ipv4']['address'] }}"
nfs_dossier: /tmp/apache
