---
# UFW
lb1_ip: hostvars['lb1']['ansible_default_ipv4']['address']
ufw_enable: true
ufw_default_input_policy: REJECT
ufw_rules: [
        { from_ip: "{{ lb1_ip }}", port: 80, proto: tcp, comment: "HTTP: allow from {{ lb1_ip }}" }
]