---
#créé le fichier de configuration du site grace a un template.
- name: add template site
  template:
    src: site-test.j2
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
#  validate: "apachectl -t -f %s"


#enbled le site si il ne l'ai pas déja.
- name: Create a symbolic link
  file:
    src: "/etc/apache/sites-available/{{ vhost_conf_file }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ vhost_conf_file }}.conf"
    owner: root
    group: root
    state: link
  notify: restart apache2


- name: disable conf
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2
- name: disable conf
  file:
    path: /etc/apache2/sites-enabled/default-ssl.conf
    state: absent
  notify: restart apache2