---
#créé le fichier de configuration du site grace a un template.
- name: add template site
  template:
    src: site-test.j2
    dest: "/etc/apache2/sites-available/{{ vhost_conf_file }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  validate: "apachectl -t -f %s"


#enbled le site si il ne l'ai pas déja.
- name: enable conf
  command:
    cmd: "a2ensite {{ vhost_conf_file }}.conf"
    creates: "/etc/apache2/sites-enabled/{{ vhost_conf_file }}.conf"

- name: disable conf
  command:
    cmd: a2dissite 000-default.conf
    creates: /etc/apache2/sites-enabled/000-default.conf


- name: disable conf
  command:
    cmd: a2dissite default-ssl.conf
    creates: /etc/apache2/sites-enabled/default-ssl.conf

- name: restart
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2
    enabled: yes
    masked: no
#- name: stat foo
#  stat: path=/path/to/foo
#  register: foo_stat
#
#  when: foo_stat.stat.exists
