---
- name: add template site
  template:
    src: site-test.j2
    dest: "/etc/apache2/sites-available/{{vhost_name_site}}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: available conf
  command: 
    cmd: "a2ensite {{vhost_name_site}}.conf"
    creates: "/etc/apache2/sites-enabled/{{vhost_name_site}}.conf"