---
- name: add template site
  template:
    src: "{{vhost_name_site}}.j2"
    dest: /etc/apache2/sites-available/site-test.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: available conf
  command: a2ensite site-test.conf