---
- name: decompress
  unarchive:
    src: wordpress-5.3-fr_FR.tar.gz
    dest: "{{ vhost_root_directory }}"

- name: add template config mysql
  template:
    src: wordpress-config-db.j2
    dest: "{{ vhost_root_directory }}"
    owner: root
    group: root
    mode: 0644
    backup: yes