---
- name: copy wordpress tar
  copy:
    src: /../../../wordpress/wordpress-5.3-fr_FR.tar.gz
    dest: /tmp
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: decompress
  command: 
    cmd: tar -zxf /tmp/wordpress-5.3-fr_FR.tar.gz -C /tmp
    creates: /var/www/license.txt

- name: decompress
  command: 
    cmd: mv /tmp/wordpress/* /var/www/
    creates: /var/www/license.txt

- name: add template config mysql
  template:
    src: wordpress-config-db.j2
    dest: /var/www/
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: rm tmp files
  command: 
    cmd: rm -rf /tmp/wordpress
    creates: /tmp/wordpress

- name: rm tmp files
  command: 
    cmd: rm /tmp/wordpress-5.3-fr_FR.tar.gz
    creates: /tmp/wordpress-5.3-fr_FR.tar.gz