stages:
  - lint

yaml_linting:
  tags:
    - docker
  stage: lint
  image: alpine:ansible-lint
  script:
    - find roles -maxdepth 1 -type d | xargs ansible-lint
  only:
    changes:
      - "*.yml"
      - host_vars/*.yml
      - group_vars/*.yml
      - roles/**/**/*.yml