---
- name: decompress
  unarchive:
    src: wordpress-5.3-fr_FR.tar.gz
    dest: /var/www

- name: add template config mysql
  template:
    src: wordpress-config-db.j2
    dest: "{{ vhost_root_directory }}/wp-config.php"
    owner: www-data
    group: www-data
    mode: 0640
    backup: true
