---
- name: install nfs
  apt:
    name: nfs-kernel-server
    update_cache: true

- name: deploying nfs config
  template:
    src: exports.j2
    dest: /etc/exports
    mode: 0644
  notify:
    - reload nfs
