---
- name: Create mariadb user any
  mysql_user:
    name: "{{ database_username }}"
    password: "{{ database_user_password }}"
    priv: '{{ database_name }}.*:ALL'
    host_all: yes
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
