---
- name: Create a database "{{ database_name }}"
  mysql_db:
     name: "{{ database_name }}"
     login_user: "{{ mariadb_login_user }}"
     login_password: "{{ mariadb_login_password }}"
     login_unix_socket: "{{ mariadb_socket }}"
     state: present
  notify: import dump file
  #register: db_created