---
# tasks file for common
- include_tasks: install_requirements.yaml
- include_tasks: install_mariadb.yaml
- include_tasks: configure_mariadb.yaml
#- include_tasks: mariadb_root_password.yaml
- include_tasks: create_database.yaml
#- include_tasks: import_dump_file_into_database.yaml
- include_tasks: create_mariadb_user.yaml
