---
- name: Add rules default (prevent self blocking SSH)
  ufw:
    rule: allow
    port: "22"
    proto: tcp
    comment: "SSH: from anywhere; prevent self blocking"

- name: Add custom rules
  ufw:
    rule: "{{ item.rule if item.rule is defined else 'allow' }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  loop: "{{ ufw_rules }}"
  when: ufw_rules is defined
