---
- name: Converge
  hosts: all

  vars:
    haproxy_port: 8080
    mariadb_replication_user: slave
    mariadb_replication_password: h!KDdGrq!Z2cYf!d#n
    mariadb_replication_role: master
    database_ip: 0.0.0.0
    ufw_enable: false   # FIXME bug with docker "ERROR: problem running sysctl"
    vip_priority: 150
    vip_ip: 192.168.1.150
    vip_mask: 24
    vip_broadcast: 192.168.1.255
    mariadb_replication_master: 0.0.0.0
    haproxy_ip_server_web1: 192.168.1.150
    haproxy_ip_server_web2: 192.168.1.151

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=600
    - name: Install dbus
      apt: name=dbus
    - name: Start dbus
      systemd: name=dbus state=started daemon_reload=true enabled=true masked=false

  roles:
    - role: hostname
    - role: ufw
    - role: mariadb
    - role: mariadb-replication
    - role: apache
    - role: wordpress
    - role: haproxy
    - role: vip
