---
- name: install nfs
  apt:
    name: nfs-common
    update_cache: true

#- name: /etc/fstab
#  lineinfile:
#    path: /etc/fstab
#    line: '{{ nfs1_ip }}:{{ nfs_dossier }}  {{ nfs_dossier }}   nfs    soft,timeo=5,intr,rsize=8192,wsize=8192  0  0'

- name: /etc/default/nfs-common
  lineinfile:
    path: /etc/default/nfs-common
    line: 'NEED_IDMAPD=yes'

- name: Create a directory /var/www
  file:
    path: /var/www
    owner: www-data
    group: www-data
    state: directory
    mode: '0755'

- name: Mount nfs4
  mount:
    name: /var/www
    src: "{{ nfs1_ip}}:{{ nfs_dossier }}" 
    fstype: nfs4
    opts: rw,relatime
    state: mounted
