---
# defaults file for common
vhost_alias: wordpress.example.local
vhost_root_directory: /var/www/wordpress
vhost_log: /var/log/apache2/site.log
vhost_conf_file: wordpress
database_ip: 192.168.43.91
