---
# mariadb_root_password: password
mariadb_socket: /var/run/mysqld/mysqld.sock
mariadb_login_user: root
mariadb_login_password: password
mariadb_dump_import: "wordpress.sql"

# UFW
web1_ip: hostvars['web1']['ansible_default_ipv4']['address']
web2_ip: hostvars['web2']['ansible_default_ipv4']['address']
ufw_enable: true
ufw_default_input_policy: REJECT
ufw_rules: [
        { from_ip: "{{ web1_ip }}", port: 3306, proto: tcp, comment: "MySQL: allow 3306 from {{ web1_ip }}" },
        { from_ip: "{{ web1_ip }}", port: 3306, proto: tcp, comment: "MySQL: allow 3306 from {{ web1_ip }}" }
]
