---
mariadb_socket: /var/run/mysqld/mysqld.sock
mariadb_login_user: root
mariadb_login_password: ChangeMe
mariadb_dump_import: "wordpress.sql"

# MariaDB replication
mariadb_replication_role: master

# UFW
db2_ip: "{{ hostvars['db2']['ansible_default_ipv4']['address'] }}"
ufw_rules: [
        { from_ip: "{{ db2_ip }}", port: 3306, proto: tcp, comment: "MySQL replication: allow 3306 from {{ db2_ip }}" }
]
