---
- name: install keapalived
  apt:
    name: keapalived
    update_cache: true

- name: deploying keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  notify:
    - reload keepalived
